SphereII/SphereII.Mods

- 0-SphereIICore/Scripts/Entities/EntityAliveSDX.cs
Overrides EntityAlive.OnAddedToWorld to (re)set the IsSleeping property, and current order (defaults to "wander").
> NPCs spawn in awake and with a current order

- 0-SCore/Scripts/Entities/EntityAliveSDX.cs
- 0-SCore/Scripts/UtilityAI/UAISCoreUtils.cs
The previous code would not allow entities to be damaged if they were not an enemy. That included a faction check, which meant that players could not damage entities at all unless they were in a "Hate" relationship with that entity's faction.
The new code changes this check so that entities can be damaged by _merely potential_ enemies.
There are also new changes to handle multiplayer. If the target, leader, or target's leader are players, it calls the vanilla FriendlyFireCheck code that takes multiplayer settings into account.
It also calls the new code to check if entities can see through blocks that collide with their weapons/ammo (missed when merging by hand).
> Fixed issue with damaging potential entities

- 0-SCore/Scripts/UtilityAI/Filters/UAIFilterIsAlly.cs
- 0-SCore/Scripts/UtilityAI/UAISCoreUtils.cs
The UAIFilterIsAlly code called SCoreUtils.IsAlly, but that only checks if the target has the same leader as yourself. It didn't include the entity itself (nor members of its own faction), so it always failed if the NPC didn't have a leader.
Changed by creating a new method, SCoreUtils.IsFriend, that includes itself, and anything that is not a "potential enemy" according to SCoreUtils.IsEnemyOrPotentialEnemy.
This should fix NPCMOD-SP-0024 in the NPCMod bug list.
> IsAlly will no longer rely on leaders

- 0-SCore/Harmony/NPCFeatures/EntityAlivePatcher.cs
- 0-SCore/Scripts/Entities/EntityAliveSDX.cs
- 0-SCore/Scripts/Entities/EntityUtilities.cs
- 0-SCore/Scripts/UtilityAI/UAISCoreUtils.cs
* Harmony prefix to EntityAlive.DamageEntity now uses SCoreUtils.CanDamage, because IsAnAlly will fail if the checking entity is the leader of the damaging entity
* EntityAliveSDX.CanDamageEntity now uses SCoreUtils.CanDamage as well
* Added EntityUtilities.GetFactionRelationship to deal with entities (like players) that don't have faction entries in npcs.xml
* SCoreUtils.IsEnemyOrPotentialEnemy now checks to see if you are the target's leader (when it has one)
> Targeting fixes

- 0-SCore/Harmony/EAI/EAITarget.cs
- 0-SCore/Harmony/MiniTurret/shouldIgnoreTarget.cs
- 0-SCore/Harmony/NPCFeatures/EntityAlivePatcher.cs
- 0-SCore/ReadMe.md
- 0-SCore/Scripts/Entities/EntityAliveSDX.cs
- 0-SCore/Scripts/Entities/EntityTargetingUtilities.cs
- 0-SCore/Scripts/UtilityAI/Filters/UAIFilterIsAlly.cs
- 0-SCore/Scripts/UtilityAI/Filters/UAIFilterIsEnemy.cs
- 0-SCore/Scripts/UtilityAI/UAIConsiderationTargetFactionStandingSDX.cs
- 0-SCore/Scripts/UtilityAI/UAISCoreUtils.cs
- 0-SCore/Scripts/UtilityAI/UAITaskIdle.cs
Refactored entity targeting methods into new EntityTargetingUtilities class.
Also refactored the methods themselves. Quite a bit of logic went into the method that determines "friendly fire" among NPCs (and players, and leaders), and extra helper methods were added that will be filled in later if/when we get feature requests.
The only behavioral changes:
* Non-enemy entities can't damage the player at all with friendly fire. They will not be able to damage the player unless the player damages them first.
* In the places where there is an "enemy check" to see if the entity's leader is targeted, it has been expanded to all allies (not just the leader).
> A20 UAI refactor

- 0-SCore/Config/blocks.xml
- 0-SCore/Harmony/Faction/FactionRelationshipCVars.cs
* Added Harmony patch of EntityPlayerLocal.Update (largely unchanged since A19, but tested)
* Added config feature block property to enable
> Add faction relationships as read-only cvars

- 0-SCore/Scripts/Entities/EntityTargetingUtilities.cs
- 0-SCore/Scripts/Entities/EntityUtilities.cs
* NPCs use only revenge target for determining whether they're attacking a leader/followers; players use either attack or revenge target, revenge target takes priority
* Added check for IsPlayerFaction when getting faction relationship (since players do have their own faction but it always returns "Neutral")
> More targeting fixes

- 0-SCore/Scripts/Entities/EntityUtilities.cs
Hopefully for the last time this time.
Our previous understanding was incorrect. Here's how it actually works:
* If self is a player, it will have a non-null faction, but its relationships with all other factions will be 400 (Neutral), so we can't use their faction to accurately determine relationships.
* If self is an NPC with a faction property (or inherited faction property) in its entity class XML, it will have a non-null, named faction as defined in npcs.xml. However, if npcs.xml does not define a relationship to its own faction - and so far, none do - then its relationship to its own faction will be whatever "*" is in npc.xml (and not "Love").
* If self is an NPC without a faction property in its entity class XML (or inherited faction property), it will have a faction ID of zero. …
> Fixed GetFactionRelationship

- 0-SCore/Scripts/Entities/EntityAliveSDX.cs
This allows friendly entities spawned with the player as their attack target (in "attack" sleeper volumes, quest actions, etc.) to interact with the player.
> Entity will only bypass activation commands if target can be damaged

- 0-SCore/Scripts/Entities/EntityTargetingUtilities.cs
For now, vehicles ignore damage from all NPCs. In the future, we might add different rules, but we have to finalize those rules first.
> NPCs cannot damage vehicles

- 0-SCore/Config/blocks.xml
- 0-SCore/Harmony/NPCFeatures/EntityAlivePatcher.cs
The new XML property should default to false, or else anyone who installs SCore without NPCCore will get a broken game.
NPCCore will need to change this value.
> New feature flag for all entities using faction-based targeting

- 0-SCore/Harmony/EAI/EAITarget.cs
This should fix issues with targeting if SCore is installed but NPCCore is not.
For example, before this change, bears could not attack players: they are in the animal faction, which is neutral to players in vanilla.
> EAITarget.check patch checks feature flag before doing faction check

- 0-SCore/Scripts/Entities/EntityAliveSDX.cs
- 0-SCore/Scripts/Entities/EntityTargetingUtilities.cs
* Changed EntityAliveSDX.OnEntityActivated to not activate only if the revenge target can be damaged (same logic as GetActivationCommands)
* Modified EntityTargetingUtilities.CanDamage so that "player friendly fire" settings are always checked, not just when the entity or its target is a player
> Fixes for NPCMOD-SP-0038 and NPCMOD-DEDI-0007

- 0-SCore/Scripts/Entities/EntityTargetingUtilities.cs
- 0-SCore/Scripts/Entities/EntityUtilities.cs
- 0-SCore/Scripts/Features/AdvLogging.cs
- 0-SCore/Scripts/UtilityAI/UAISCoreUtils.cs
* Refactored EntityTargetingUtilities.IsEnemy to remove calls to CanDamage, reducing redundant checks, improving performance
* If EntityUtilities.GetLeaderOrOwner needs to acquire the leader from expensive calls, the leader is cached automatically (doesn't rely on callers invoking SetLeaderAndOwner)
* Removed last string param from both versions of AdvLogging.LogEnabled (was causing callers that passed AdvFeatureClass, Feature to use the overload where Feature would be considered strDisplay)
* SCoreUtils.IsEnemyNearby uses revenge target directly for initial "revenge target" check, rather than using either the attack or revenge target (the attack target may not be set by UAI, but it is set in sleeper volumes, quest spawns, etc.)
* Since IsEnemyNearby now uses revenge targets directly, it …
> Performance improvements and small bug fixes (#1)

- 0-SCore/Harmony/MiniTurret/shouldIgnoreTarget.cs
- 0-SCore/Scripts/Entities/EntityTargetingUtilities.cs
This reverts changes from the last pull request, and re-implements its features in a way that involves fewer code changes, and hopefully will not crash the game.
It also should fix an issue where player junk turrets/sledges will not target enemy animals, if SCore is installed by itself into a vanilla game (without NPC Core).
The "damage relationship" cvar has been renamed, and now holds the actual relationship value (it's no longer just a flag). If the relationship does not meet or exceed this value, the entity can be damaged.
> Redo animals faction fix, change damage faction relationship to "dislike" or below

- 0-SCore/Scripts/Entities/EntityTargetingUtilities.cs
This should fix the issue where animals (and other entities) that are neutral to the player, cannot be harmed.
It also introduces a method where we can choose this relationship by target type, as opposed to a single cvar for all targets.
It should also help when using the "IsHuman" tags, since even if an entity has that tag, it doesn't necessarily mean it should be immune from damage if it's in a neutral faction. (Consider companion animals that need to be tamed by "hitting" them with a leash.)
> Added method to return default friendly fire faction relationship

- 0-SCore/Scripts/Entities/EntityUtilities.cs
Somewhere in the code, something is trying to get either the "Leader" or "Owner" cvar value, without checking to see if it exists first. (I could not track down where.) When this happens, the cvar is created if it doesn't exist, and set with the value of zero.
When doing a playthrough test of a prefab from the prefab builder, the world includes a test trader. That trader happens to have the entity ID of zero.
As a result, all NPCs in test playthroughs will have that trader as their leader, and won't attack the player.
This fix involves ignoring the value of zero for leader and owner IDs.
> Quick fix for NPCMOD-SP-0064

- 0-SCore/Harmony/NPCFeatures/EntityAlivePatcher.cs
It turns out the culprit was `ItemActionDynamic.hitTarget` which populates the `AttackHitInfo` with a list of resources. This method is called by both `ItemActionDynamicMelee.Raycast` and by `ItemActionDynamicMelee.GrazeCast`.
Unfortunately the Harmony patch is still needed; without it, you can damage your hires.
> Fix for the "infinite harvest bug"

- 0-SCore/Scripts/Entities/EntityTargetingUtilities.cs
- 0-SCore/Scripts/Quests/QuestActionSetRevengeTargetsSDX.cs
The revenge targets were being set on all entities in bounds, including the player hires. This is now fixed, and in addition the revenge targets also will not be set on other players in the party, provided those players are protected from friendly fire.
To detect whether an entity is an ally of the player's party, I created a new `IsAllyOfParty` method in `EntityTargetingUtilities`. I did not change any existing methods so there should be no risk of breaking anything.
I also fixed an issue where the POI's full area was not covered (the `Bounds` constructor shrinks the `size` vector argument in half so only a quarter of the prefab was covered).
> Revenge targets not set on player allies; fixed bounds issue

- 0-SCore/Scripts/UtilityAI/UAITaskAttackTargetEntitySDX.cs
- 0-SCore/Scripts/UtilityAI/UAITaskMoveToInvestigate.cs
- 0-SCore/Scripts/UtilityAI/UAITaskMoveToTargetSDX.cs
This is the minimum code needed to get those sounds working.
I did not alter the way the tasks handle setting the attack target. If that is done differently in the future, then the code in `UAITaskMoveToTargetSDX` can probably be changed, since setting the attack target also sets `ApproachingEnemy` and `ApproachingPlayer`. Those values determine whether the entity plays the "SoundRandom" sound, or the "SoundAlert" sound.
> UAI tasks trigger alert, sense, and "give up" sounds

- 0-SCore/Scripts/Entities/EntityEnemySDX.cs
- 0-SCore/Scripts/UtilityAI/UAISCoreUtils.cs
* `EntityEnemySDX` overrides `GetMoveSpeed` and `GetMoveSpeedAggro` to fix issues with melee entities not running at the player when attacking
* `SCoreUtils.SetSpeed` now takes into account enemies spawned into hordes
> Move speed changes

- 0-SCore/Harmony/Animation/AvatarController.cs
- 0-SCore/Scripts/Entities/EntityEnemySDX.cs
- 0-SCore/Scripts/UtilityAI/UAIConsiderationHasInvestigatePosition.cs
- 0-SCore/Scripts/UtilityAI/UAITaskApproachSpotSDX.cs
- 0-SCore/Scripts/UtilityAI/UAITaskAttackTargetEntitySDX.cs
* Harmony patch to `AvatarZombieController` now also applies for `EntityEnemySDX`
* `EntityEnemySDX` now descends from `EntityHuman` (solves issues and allows us to get rid of redundant code)
* `UAITaskAttackTargetEntitySDX` now explicitly sets the "WeaponFire" bool when using the ranged attack (index 1, a.k.a. "Use"), and accounts for the case where the call to `Use` fails
* New UAI Task: `UAITaskApproachSpot` - based on `EAIApproachSpot` to direct entities to their investigate positions (especially when spawned into hordes)
* New UAI Consideration: `UAIConsiderationHasInvestigatePosition` - returns 1 if the target entity has an investigate position, 0 otherwise. Needed for a new action in the basic NPC Utility AI that overrides the "Wander" action.
> EntityEnemy changes for animations and spawning into hordes

- 0-SCore/Config/blocks.xml
- 0-SCore/Harmony/PlayerFeatures/PlayerMoveControllerUpdate.cs
This only happens if the "AdvancedEnemyNPCs" feature flag is enabled.
> Remove the prompt to talk with enemy NPCs

- 0-SCore/0-SCore.csproj
- 0-SCore/Config/dialogs.xml
- 0-SCore/Harmony/Dialog/DialogFromXML.cs
- 0-SCore/Scripts/Dialogs/DialogActionAddCVar.cs
- 0-SCore/Scripts/Dialogs/DialogRequirementFactionValue.cs
- 0-SCore/Scripts/Dialogs/DialogRequirementHasCVar.cs
- 0-SCore/Scripts/Dialogs/DialogRequirementIsSleeper.cs
- 0-SCore/Scripts/Dialogs/DialogRequirementLeader.cs
- 0-SCore/Scripts/Dialogs/DialogRequirementNPCHasCVar.cs
- 0-SCore/Scripts/Dialogs/IDialogOperator.cs
* Added `IDialogOperator` interface for requirements and actions that accept an "operator" attribute
* Updated Harmony patches to `DialogFromXML` to use the interface
* `DialogActionAddCVar`, `DialogRequirementFactionValue`, `DialogRequirementHasCvar`, and `DialogRequirementNPCHasCVar` now all implement that interface
* Major refactoring of `DialogRequirementNPCHasCVar`
* `DialogRequirementHasCVar` handles "not" operator better
* `DialogRequirementLeader` supports "not" as a value, which checks that the NPC is not hired by the player talking to it (as opposed to "HiredSDX" which just checks whether or not the NPC is hired by _any_ player)
* Added XPath in `dialogs.xml` that will test the various values of "HasCVarSDX" (the XPath is commented out)
> Dialog requirement changes

- 0-SCore/Scripts/Entities/EntityTargetingUtilities.cs
The "followers of followers" issue is solved by replacing calls to `EntityUtilities.GetLeaderOrOwner` with calls to a new method that searches the "chain of command" until it finds a leader/owner that does not itself have a leader/owner.
The issue with explosions was not actually an issue with explosions. It was an issue with the `CanDamage` method.
That method was checking to see if both `self` and `target` have leaders who are players, and if so, uses the vanilla `FriendlyFireCheck` method to see if one player can damage another.
But hires have a player leader - their leader - and the player also has a "player leader" - itself. And the vanilla `FriendlyFireCheck` method allows players to damage themselves (which is how they can be set on fire by their own Molotovs).
So `CanDamage` was …
> Fix for issues with explosions and "followers of followers"

- 0-SCore/0-SCore.csproj
- 0-SCore/Config/buffs.xml
- 0-SCore/Harmony/EntityAlive/EntityAlivePatches.cs
- 0-SCore/Scripts/Buffs/FactionRelationshipValue.cs
- 0-SCore/Scripts/Buffs/TargetCVarCompare.cs
- 0-SCore/Scripts/MinEvents/MinEventActionSetRevengeTarget.cs
* New Harmony patches to `EntityAlive` to set read-only cvars of entity, attack target, revenge target IDs
* New `FactionRelationshipValue` buff requirement - compares relationship to a value or name of a relationship
* New `TargetCVarCompare` buff requirement - compares "self" cvar value with target cvar value
* New `MinEventActionSetRevengeTarget` action - sets/resets the revenge target (0 or lower resets to null)
* Example buffs in `buffs.xml`
> Changes for NPC "forgiveness"/reset revenge target

- Mods/0-SCore/Scripts/Entities/EntityTargetingUtilities.cs
This was a mistake done when fixing the issues with explosions and "followers of followers."
Commit where it happened:
https://github.com/SphereII/SphereII.Mods/commit/65d4e5a1b0d281623e720e3813b630cccca435d8
> Fix mistaken swap of self and target for friendly fire check

- Mods/0-SCore/Harmony/EAI/EAITarget.cs
- Mods/0-SCore/Harmony/NPCFeatures/EntityAlivePatcher.cs
- Mods/0-SCore/Scripts/Entities/EntityUtilities.cs
This is a Harmony patch on `ItemActionDynamic.hitTarget` to disable the firing of "onSelf[Primary|Secondary]Action[Ray|Graze]Hit" events if the holding entity can't damage the target entity.
This is the cause of the stun baton "shock" issue with friendly NPCs. The stun baton itself wasn't hitting or doing damage, but the baton was still charging, and when fully charged, it still shocked the friendly NPC.
I also refactored the logic to determine when an entity should use faction targeting. It was already repeated in two places in the code, and I would need to repeat it a third time in my patch.
I did test to make sure that there were no regressions. I tested with a friendly NPC (Baker), an enemy NPC (Harley), an animal (bear), and zombies (mainly Boe). I made sure that I could still shock …
> Disable ray hit events when entities can't be damaged
